#!/bin/bash
# Phase 1 Twilio Integration Testing Guide
# This script helps set up and test real Twilio integration

set -e

echo "🔧 Phase 1 Twilio Integration - Setup & Testing Guide"
echo "======================================================"
echo ""

# Check if we're in the right directory
if [ ! -f "package.json" ]; then
  echo "❌ Error: Please run this script from the project root directory"
  exit 1
fi

# Check required commands
check_command() {
  if ! command -v $1 &> /dev/null; then
    echo "❌ $1 is not installed. Please install it first."
    exit 1
  fi
}

check_command "node"
check_command "npm"

echo "✅ Project dependencies found"
echo ""

# Step 1: Verify environment setup
echo "📋 Step 1: Verify Environment Configuration"
echo "============================================"
echo ""
echo "Required environment variables for Twilio:"
echo "  - TWILIO_ACCOUNT_SID"
echo "  - TWILIO_AUTH_TOKEN"
echo "  - TWILIO_PHONE_NUMBER"
echo "  - TWILIO_WEBHOOK_URL (must be publicly accessible)"
echo ""
echo "To get these values:"
echo "  1. Go to https://www.twilio.com/console"
echo "  2. Copy your Account SID and Auth Token"
echo "  3. Set up a Twilio phone number (or use existing)"
echo "  4. Note the phone number in E.164 format (+1XXXYYYZZZZ)"
echo ""

# Step 2: Check .env file
if [ -f ".env" ]; then
  echo "✅ .env file found"
  if grep -q "TWILIO_ACCOUNT_SID" .env; then
    echo "✅ TWILIO_ACCOUNT_SID is configured"
  else
    echo "⚠️  TWILIO_ACCOUNT_SID not found in .env"
    echo "   Add: TWILIO_ACCOUNT_SID=your_account_sid"
  fi
else
  echo "❌ .env file not found"
  echo "   Copy .env.example to .env and fill in Twilio credentials"
  cp .env.example .env
  echo "✅ Created .env from .env.example (please edit with your credentials)"
fi

echo ""
echo "📋 Step 2: Public Webhook URL Setup (for local testing)"
echo "======================================================"
echo ""
echo "For local development, you need to expose your local server to the internet."
echo "Options:"
echo ""
echo "A) Using ngrok (recommended for development):"
echo "   1. Install ngrok: https://ngrok.com/download"
echo "   2. Run: ngrok http 3000"
echo "   3. Copy the https URL from ngrok output"
echo "   4. Set in .env: TWILIO_WEBHOOK_URL=https://your-ngrok-url.ngrok.io"
echo ""
echo "B) Using localtunnel:"
echo "   1. npm install -g localtunnel"
echo "   2. Run: lt --port 3000"
echo "   3. Copy the URL from output"
echo "   4. Set in .env: TWILIO_WEBHOOK_URL=https://your-url.loca.lt"
echo ""
echo "C) Deploy to production/staging:"
echo "   1. Deploy app to cloud server"
echo "   2. Set TWILIO_WEBHOOK_URL to your production URL"
echo ""

echo "📋 Step 3: Configure Twilio Phone Number"
echo "=========================================="
echo ""
echo "1. Go to https://www.twilio.com/console/phone-numbers/incoming"
echo "2. Select your Twilio phone number"
echo "3. Under 'Voice Configuration':"
echo "   - Set 'A Call Comes In' to: Webhook"
echo "   - URL: https://your-webhook-url/api/integrations/twilio/voice-webhook"
echo "   - Method: POST"
echo ""

echo "📋 Step 4: Start the Application"
echo "================================="
echo ""
echo "To start the server for local testing:"
echo "  npm start      (production mode)"
echo "  npm run dev    (watch mode for development)"
echo ""

echo "📋 Step 5: Verify API Health"
echo "============================="
echo ""
echo "After starting the server, verify endpoints are working:"
echo ""
echo "Test health endpoint:"
echo "  curl http://localhost:3000/health"
echo ""
echo "Test Twilio integration endpoint:"
echo "  curl -X POST http://localhost:3000/api/integrations/twilio/voice-webhook \\"
echo "    -H 'Content-Type: application/x-www-form-urlencoded' \\"
echo "    -d 'From=%2B1234567890&To=%2B1987654321&CallSid=CA12345678'"
echo ""

echo "📋 Step 6: Make a Test Call"
echo "==========================="
echo ""
echo "Scenario: Test phone-to-order flow"
echo ""
echo "1. Have your server running:"
echo "   npm start"
echo ""
echo "2. Start ngrok to expose local server:"
echo "   ngrok http 3000"
echo ""
echo "3. Update Twilio phone number webhook URL to ngrok URL:"
echo "   https://your-ngrok-url.ngrok.io/api/integrations/twilio/voice-webhook"
echo ""
echo "4. Call your Twilio phone number from any phone"
echo ""
echo "5. Speak your shipment details:"
echo "   'Pickup from Phoenix to Los Angeles on July 16'"
echo "   'Weight 5000 kilograms, volume 40 cubic meters'"
echo "   'Electronics shipment'"
echo ""
echo "6. Verify in server logs:"
echo "   - Inbound call logged"
echo "   - Recording completed"
echo "   - Transcription processed"
echo "   - Order created (check database or /api/orders endpoint)"
echo ""

echo "📋 Step 7: Verify Order Creation"
echo "================================="
echo ""
echo "Query orders via API:"
echo "  curl http://localhost:3000/api/orders"
echo ""
echo "Get specific order:"
echo "  curl http://localhost:3000/api/orders/{order-id}"
echo ""
echo "Expected response includes:"
echo "  - customer_name: from transcription"
echo "  - origin: pickup location"
echo "  - destination: dropoff location"
echo "  - weight_kg: parsed weight"
echo "  - volume_m3: parsed volume"
echo "  - cargo_type: identified commodity"
echo "  - status: 'normalized' or 'sent_to_fleetbase'"
echo ""

echo "📋 Step 8: Generate Quote"
echo "=========================="
echo ""
echo "Create a quote from the order:"
echo "  curl -X POST http://localhost:3000/api/orders/{order-id}/quotes"
echo ""
echo "Expected response includes:"
echo "  - base_price: calculated from distance + weight + volume"
echo "  - discount_amount: from load optimization agent"
echo "  - final_price: after discount"
echo "  - status: 'approved' or 'requires_manual_review'"
echo ""

echo "📋 Step 9: Troubleshooting"
echo "=========================="
echo ""
echo "Issue: Webhook not receiving calls"
echo "  ✓ Verify ngrok/localtunnel is running"
echo "  ✓ Check webhook URL in Twilio console matches"
echo "  ✓ Verify firewall allows HTTPS (port 443)"
echo ""
echo "Issue: Transcription not working"
echo "  ✓ Check OPENAI_API_KEY is set in .env"
echo "  ✓ Verify audio quality (clear speech)"
echo "  ✓ Check server logs for Whisper API errors"
echo ""
echo "Issue: Order not created"
echo "  ✓ Check triage confidence score in logs (should be > 0.6)"
echo "  ✓ Verify all required fields extracted (pickup, dropoff, weight, volume)"
echo "  ✓ Check for duplicate order (same customer within 1 hour)"
echo ""
echo "Issue: Database errors"
echo "  ✓ Verify DATABASE_URL is set"
echo "  ✓ Run database schema: npm run db:migrate"
echo "  ✓ Check PostgreSQL is running and accessible"
echo ""

echo "📋 Step 10: Monitoring & Logs"
echo "============================="
echo ""
echo "Watch server logs in real-time:"
echo "  npm run dev"
echo ""
echo "Key log messages to watch for:"
echo "  - 'Inbound call received' - webhook is working"
echo "  - 'Recording completed' - Twilio recorded audio"
echo "  - 'Whisper transcription completed' - speech-to-text worked"
echo "  - 'Step 1: Running triage validation' - order intake started"
echo "  - 'Order created successfully' - order in database"
echo ""

echo ""
echo "✅ Setup Guide Complete!"
echo ""
echo "Next steps:"
echo "1. Configure Twilio credentials in .env"
echo "2. Set up public webhook URL (ngrok recommended)"
echo "3. Start server: npm start"
echo "4. Make a test call to your Twilio number"
echo "5. Check server logs and /api/orders endpoint"
echo ""
